- shields:
    style: 'flat-square'
    shields:
      - alt: 'flipactual'
        image: 'badge/😋-flipactual-218AC7.svg'
        link: 'https://www.flipactual.com/'
      - alt: 'Travis'
        image: 'travis/flipactual/get-euclidean-distance.svg'
        link: 'https://travis-ci.org/flipactual/get-euclidean-distance/'
      - alt: 'Node'
        image: 'node/v/get-euclidean-distance.svg'
        link: 'http://npmjs.com/package/get-euclidean-distance'
      - alt: 'NPM'
        image: 'npm/v/get-euclidean-distance.svg'
        link: 'http://npmjs.com/package/get-euclidean-distance'
- include: './docs/scripts.md'
- jsdoc: 'index.js'
- license: true
